name: generate-openapi-schema

on:
  push

jobs:
  generate-openapi-schema:
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt
    - run: python generate-openapi.py
    - name: test
      run: |
        git config --global user.name "CI"
        git config --global user.email "username@users.noreply.github.com"
        git commit --all --message "[CI] generate openapi schema"
        git push
