name: generate-openapi-schema

on:
  push

jobs:
  generate-openapi-schema:
    runs-on: ubuntu-latest
    environment: ci
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt
    - env:
        APP_ENV: CI
        APP_COMPONENT: api
        APP_HOST: 0.0.0.0
        APP_PORT: 80
        LOG_LEVEL: 10
        READ_DB_DRIVER: postgres
        READ_DB_USER: postgres
        READ_DB_PASS: abc123
        READ_DB_HOST: localhost
        READ_DB_PORT: 5432
        READ_DB_NAME: test_db
        WRITE_DB_DRIVER: postgres
        WRITE_DB_USER: postgres
        WRITE_DB_PASS: abc123
        WRITE_DB_HOST: localhost
        WRITE_DB_PORT: 5432
        WRITE_DB_NAME: test_db
        MIN_DB_POOL_SIZE: 0
        MAX_DB_POOL_SIZE: 10
        DB_USE_SSL: false
      run: python generate-openapi.py
    - name: Commit openapi schema
      run: |
        git config --global user.name "CI"
        git config --global user.email "username@users.noreply.github.com"
        git commit --all --message "[CI] generate openapi schema"
        git push
