name: test

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build application
      run: docker build -t example-service:latest .
    - name: run containers
      run: docker-compose up -d example-service mysql
    - name: run tests
      run: |
        docker-compose exec --no-TTY example-service /scripts/test.sh 2> errors.txt || true
        cat errors.txt
    - name: stop containers
      run: docker-compose down
