name: test

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build application
      run: docker build -t example-service:latest .
    - name: run containers
      run: docker-compose up -d example-service mysql
    - name: run tests 2
      run: echo "what u p"
    - name: run tests 1
      run: |
        ls
        ls -l
        echo what
        docker-compose exec -T example-service echo test >> abc 2>> abc
        echo what2
        ls
        ls -l
        cat abc
    - name: stop containers
      run: docker-compose down
