name: test

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build application
      run: make build
    - name: run containers
      run: make run-bg
    - name: run tests
      run: make test
    - name: stop containers
      run: docker-compose down
